#[derive(Debug, Clone, PartialEq)]
pub enum TokenKind {
    // Literals
    Int(i64),
    Float(f64),
    String(String),
    Char(char),
    Bool(bool),

    Ident(String),
    Kw(Kw),
    Lifetime(String),

    // Multi-char operators
    ColonEq,
    MutColonEq,
    DotDot,
    DotDotEq,
    PlusPlus,
    PipeGt,
    StarStar,
    AmpAmpAmp,
    PipePipePipe,
    CaretCaretCaret,
    Ne,
    Le,
    Ge,
    EqEq,
    And,
    Or,
    PlusEq,
    MinusEq,
    StarEq,
    SlashEq,
    PercentEq,
    AmpMut,
    Arrow,
    Shl,
    Shr,

    // Single-char / short
    Plus,
    Minus,
    Star,
    Slash,
    Percent,
    Bang,
    Question,
    Amp,
    Pipe,
    Caret,
    Tilde,
    Assign,
    Colon,
    Comma,
    Semi,
    Dot,
    Lt,
    Gt,

    LParen,
    RParen,
    LBrace,
    RBrace,
    LBracket,
    RBracket,

    Eof,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Kw {
    If,
    Then,
    Else,
    Match,
    With,
    For,
    In,
    While,
    Do,
    Loop,
    Return,
    Break,
    Continue,
    Type,
    Trait,
    Shape,
    Impl,
    Own,
    Mut,
    Ref,
    Shared,
    Rc,
    Arc,
    Async,
    Await,
    Spawn,
    Use,
    As,
    Mod,
    Pub,
    True,
    False,
    None,
    Some,
    Catch,
    Throw,
    Panic,
    Unsafe,
    Extern,
    Test,
    TestCompileFail,
}

impl Kw {
    pub fn lookup(s: &str) -> Option<Self> {
        Some(match s {
            "if" => Self::If,
            "then" => Self::Then,
            "else" => Self::Else,
            "match" => Self::Match,
            "with" => Self::With,
            "for" => Self::For,
            "in" => Self::In,
            "while" => Self::While,
            "do" => Self::Do,
            "loop" => Self::Loop,
            "return" => Self::Return,
            "break" => Self::Break,
            "continue" => Self::Continue,
            "type" => Self::Type,
            "trait" => Self::Trait,
            "shape" => Self::Shape,
            "impl" => Self::Impl,
            "own" => Self::Own,
            "mut" => Self::Mut,
            "ref" => Self::Ref,
            "shared" => Self::Shared,
            "rc" => Self::Rc,
            "arc" => Self::Arc,
            "async" => Self::Async,
            "await" => Self::Await,
            "spawn" => Self::Spawn,
            "use" => Self::Use,
            "as" => Self::As,
            "mod" => Self::Mod,
            "pub" => Self::Pub,
            "true" => Self::True,
            "false" => Self::False,
            "none" => Self::None,
            "some" => Self::Some,
            "catch" => Self::Catch,
            "throw" => Self::Throw,
            "panic" => Self::Panic,
            "unsafe" => Self::Unsafe,
            "extern" => Self::Extern,
            "test" => Self::Test,
            "test_compile_fail" => Self::TestCompileFail,
            _ => return None,
        })
    }
}

#[derive(Debug, Clone, PartialEq)]
pub struct Token {
    pub kind: TokenKind,
    pub start: u32,
    pub end: u32,
}
