//! Pretty-print CIR to idiomatic Rust (spec §17.1).

use crate::source_map::EmitSourceMap;
use crisp_cir::{
    CirBinOp, CirBlock, CirCatchArm, CirCrate, CirExpr, CirFunction, CirItem, CirModule, CirParam,
    CirPat, CirShapeTrait, CirStmt, CirStruct, CirTy, CirVariant, CirWithFn,
};
use crisp_errors::format_crisp_error_enum;
use crisp_ownership::OwnershipMode;
use crisp_resolve::stdlib::std_rust_path;
use std::fmt::Write;

pub struct EmitResult {
    pub lib_rs: String,
    pub modules: Vec<(String, String)>,
    pub source_map: EmitSourceMap,
}

pub fn emit_crate(cir: &CirCrate) -> EmitResult {
    let mut map = EmitSourceMap::default();
    let mut modules = Vec::new();

    if cir.modules.len() == 1 && cir.modules[0].path == "main" {
        let mut out = String::new();
        emit_prelude(&mut out, cir);
        emit_module_items(&mut out, &cir.modules[0], cir, &mut map, true);
        return EmitResult {
            lib_rs: out,
            modules,
            source_map: map,
        };
    }

    let mut main_rs = String::new();
    emit_prelude(&mut main_rs, cir);

    // Leaf bodies keyed by dotted module path (`math.vector`).
    let mut leaf_bodies: std::collections::BTreeMap<String, String> =
        std::collections::BTreeMap::new();
    for m in &cir.modules {
        if m.path == "main" {
            continue;
        }
        let mut mod_src = String::new();
        emit_module_items(&mut mod_src, m, cir, &mut map, false);
        leaf_bodies.insert(m.path.clone(), mod_src);
    }

    // Build the full path tree (including intermediate parents) for nested emit (#35).
    let mut tree_paths: std::collections::BTreeSet<String> = std::collections::BTreeSet::new();
    for path in leaf_bodies.keys() {
        let mut prefix = String::new();
        for seg in path.split('.') {
            if !prefix.is_empty() {
                prefix.push('.');
            }
            prefix.push_str(seg);
            tree_paths.insert(prefix.clone());
        }
    }

    for path in &tree_paths {
        let children = direct_child_segments(&tree_paths, path);
        let mut src = String::new();
        for child in &children {
            let _ = writeln!(src, "pub mod {child};");
            let _ = writeln!(src, "pub use {child}::*;");
        }
        if let Some(body) = leaf_bodies.get(path) {
            src.push_str(body);
        }
        modules.push((path.clone(), src));
    }

    // Crate root: declare only top-level modules (not `math.vector`).
    let top_level = direct_child_segments(&tree_paths, "");
    for top in &top_level {
        let _ = writeln!(main_rs, "mod {top};");
        let _ = writeln!(main_rs, "pub use {top}::*;");
    }

    // Emit all main-module items (structs/enums/impls/fns). Previously only
    // functions were written here, which dropped enums/types next to nested mods.
    for m in &cir.modules {
        if m.path == "main" {
            emit_module_items(&mut main_rs, m, cir, &mut map, true);
        }
    }

    EmitResult {
        lib_rs: main_rs,
        modules,
        source_map: map,
    }
}

/// Direct child path segments under `parent` (empty parent = crate-root children).
fn direct_child_segments(
    tree_paths: &std::collections::BTreeSet<String>,
    parent: &str,
) -> Vec<String> {
    let mut children = Vec::new();
    for path in tree_paths {
        let child = if parent.is_empty() {
            let mut parts = path.split('.');
            let first = parts.next().unwrap_or("");
            if parts.next().is_none() {
                Some(first.to_string())
            } else {
                None
            }
        } else {
            path.strip_prefix(parent)
                .and_then(|rest| rest.strip_prefix('.'))
                .and_then(|rest| {
                    if rest.contains('.') {
                        None
                    } else {
                        Some(rest.to_string())
                    }
                })
        };
        if let Some(c) = child {
            children.push(c);
        }
    }
    children.sort();
    children.dedup();
    children
}

fn emit_prelude(out: &mut String, cir: &CirCrate) {
    let _ = writeln!(out, "// Generated by crisp — do not edit");
    let _ = writeln!(out, "#![allow(dead_code, unused_variables, clippy::all)]");
    let _ = writeln!(out);
    if !cir.crisp_error.variants.is_empty() {
        let _ = writeln!(out, "{}", format_crisp_error_enum(&cir.crisp_error));
        let _ = writeln!(out);
    }
    emit_std_trait_shims(out, cir);
    for shape in &cir.shape_traits {
        emit_shape_trait(out, shape);
    }
}

/// Spec §15.4 — inject Show/Eq/Ord when the crate did not define them locally.
fn emit_std_trait_shims(out: &mut String, cir: &CirCrate) {
    let mut defined = std::collections::BTreeSet::new();
    for m in &cir.modules {
        for item in &m.items {
            if let CirItem::Trait(t) = item {
                defined.insert(t.name.as_str());
            }
        }
    }
    if !defined.contains("Show") {
        let _ = writeln!(out, "pub trait Show {{");
        let _ = writeln!(out, "    fn show(&self) -> String;");
        let _ = writeln!(out, "}}");
    }
    if !defined.contains("Eq") {
        // Method `equal` (not `eq`) avoids clashing with PartialEq::eq after the bridge.
        let _ = writeln!(out, "pub trait Eq {{");
        let _ = writeln!(out, "    fn equal(&self, other: &Self) -> bool;");
        let _ = writeln!(out, "}}");
    }
    if !defined.contains("Ord") {
        // Method `compare` (not `cmp`) avoids clashing with std::cmp::Ord::cmp.
        let _ = writeln!(out, "pub trait Ord {{");
        let _ = writeln!(out, "    fn compare(&self, other: &Self) -> i64;");
        let _ = writeln!(out, "}}");
    }
    if !defined.contains("Show") || !defined.contains("Eq") || !defined.contains("Ord") {
        let _ = writeln!(out);
    }
}

fn emit_module_items(
    out: &mut String,
    module: &CirModule,
    cir: &CirCrate,
    map: &mut EmitSourceMap,
    include_main: bool,
) {
    for item in &module.items {
        match item {
            CirItem::Struct(s) => emit_struct(out, s, map),
            CirItem::Enum(e) => emit_enum(out, e, map),
            CirItem::Alias {
                name,
                is_pub,
                ty,
                span,
            } => {
                map.record(out.len() as u32, *span);
                let vis = if *is_pub { "pub " } else { "" };
                let _ = writeln!(out, "{vis}type {name} = {};", format_ty(ty));
            }
            CirItem::Function(f) => {
                if include_main || !f.is_main {
                    emit_function(out, f, &module.path, map, true, None, cir);
                }
            }
            CirItem::Trait(t) => emit_user_trait(out, t, map),
            CirItem::Impl(ib) => {
                if let Some(tn) = &ib.trait_name {
                    let args = format_ty_args(&ib.trait_args);
                    let _ = writeln!(out, "impl {tn}{args} for {} {{", ib.ty_name);
                } else {
                    let _ = writeln!(out, "impl {} {{", ib.ty_name);
                }
                // Trait impl methods must not carry `pub` (E0449).
                let allow_pub = ib.trait_name.is_none();
                for f in &ib.functions {
                    emit_function(
                        out,
                        f,
                        &module.path,
                        map,
                        allow_pub,
                        ib.trait_name.as_deref(),
                        cir,
                    );
                }
                let _ = writeln!(out, "}}");
                if let Some(tn) = &ib.trait_name {
                    emit_std_trait_rust_bridge(out, tn, &ib.ty_name);
                }
            }
            CirItem::Extern(ext) => emit_extern_block(out, ext, map),
        }
    }
    let _ = cir;
}

fn emit_user_trait(out: &mut String, t: &crisp_cir::CirTrait, map: &mut EmitSourceMap) {
    map.record(out.len() as u32, t.span);
    let gens = format_ty_params(&t.generics);
    let _ = writeln!(out, "trait {}{gens} {{", t.name);
    for m in &t.methods {
        let params: Vec<_> = m
            .params
            .iter()
            .map(|(n, ty)| {
                if n == "self" {
                    "&self".to_string()
                } else if matches!(t.name.as_str(), "Eq" | "Ord") {
                    format!("{n}: &Self")
                } else {
                    format!("{n}: {}", format_ty(ty))
                }
            })
            .collect();
        let ret = if matches!(m.ret, CirTy::Unit) {
            String::new()
        } else {
            format!(" -> {}", format_ty(&m.ret))
        };
        if let Some(body) = &m.default_body {
            let _ = write!(out, "    fn {}({}){} {{ ", m.name, params.join(", "), ret);
            emit_expr(out, body, "", map);
            let _ = writeln!(out, " }}");
        } else {
            let _ = writeln!(out, "    fn {}({}){};", m.name, params.join(", "), ret);
        }
    }
    let _ = writeln!(out, "}}");
}

/// Bridge Crisp Show/Eq/Ord impls to Rust Display / PartialEq+Eq / Ord (§15.4).
fn emit_std_trait_rust_bridge(out: &mut String, trait_name: &str, ty_name: &str) {
    match trait_name {
        "Show" => {
            let _ = writeln!(out, "impl std::fmt::Display for {ty_name} {{");
            let _ = writeln!(
                out,
                "    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {{"
            );
            let _ = writeln!(out, "        write!(f, \"{{}}\", Show::show(self))");
            let _ = writeln!(out, "    }}");
            let _ = writeln!(out, "}}");
        }
        "Eq" => {
            let _ = writeln!(out, "impl PartialEq for {ty_name} {{");
            let _ = writeln!(out, "    fn eq(&self, other: &Self) -> bool {{");
            let _ = writeln!(out, "        <{ty_name} as Eq>::equal(self, other)");
            let _ = writeln!(out, "    }}");
            let _ = writeln!(out, "}}");
            let _ = writeln!(out, "impl std::cmp::Eq for {ty_name} {{}}");
        }
        "Ord" => {
            let _ = writeln!(out, "impl std::cmp::Ord for {ty_name} {{");
            let _ = writeln!(
                out,
                "    fn cmp(&self, other: &Self) -> std::cmp::Ordering {{"
            );
            let _ = writeln!(
                out,
                "        match <{ty_name} as Ord>::compare(self, other) {{"
            );
            let _ = writeln!(out, "            n if n < 0 => std::cmp::Ordering::Less,");
            let _ = writeln!(out, "            0 => std::cmp::Ordering::Equal,");
            let _ = writeln!(out, "            _ => std::cmp::Ordering::Greater,");
            let _ = writeln!(out, "        }}");
            let _ = writeln!(out, "    }}");
            let _ = writeln!(out, "}}");
            let _ = writeln!(out, "impl PartialOrd for {ty_name} {{");
            let _ = writeln!(
                out,
                "    fn partial_cmp(&self, other: &Self) -> Option<std::cmp::Ordering> {{"
            );
            let _ = writeln!(out, "        Some(std::cmp::Ord::cmp(self, other))");
            let _ = writeln!(out, "    }}");
            let _ = writeln!(out, "}}");
        }
        _ => {}
    }
}

fn emit_extern_block(out: &mut String, ext: &crisp_cir::CirExternBlock, map: &mut EmitSourceMap) {
    map.record(out.len() as u32, ext.span);
    let _ = writeln!(out, "extern \"{}\" {{", ext.abi);
    for f in &ext.functions {
        map.record(out.len() as u32, f.span);
        let params: Vec<_> = f.params.iter().map(format_extern_param).collect();
        let ret = if matches!(f.ret, CirTy::Unit) {
            String::new()
        } else {
            format!(" -> {}", format_extern_ty(&f.ret))
        };
        let _ = writeln!(out, "    fn {}({}){};", f.name, params.join(", "), ret);
    }
    let _ = writeln!(out, "}}");
}

fn emit_struct(out: &mut String, s: &CirStruct, map: &mut EmitSourceMap) {
    map.record(out.len() as u32, s.span);
    let vis = if s.is_pub { "pub " } else { "" };
    let gens = format_ty_params(&s.generics);
    let _ = writeln!(out, "#[derive(Debug, Clone)]");
    let _ = write!(out, "{vis}struct {}{gens} {{", s.name);
    for (i, f) in s.fields.iter().enumerate() {
        if i > 0 {
            let _ = write!(out, ", ");
        }
        let _ = write!(out, "pub {}: {}", f.name, format_ty(&f.ty));
    }
    let _ = writeln!(out, "}}");
    if let Some(with_fn) = &s.with_fn {
        emit_with_fn(out, s, with_fn, map);
    }
}

fn emit_with_fn(out: &mut String, s: &CirStruct, with_fn: &CirWithFn, map: &mut EmitSourceMap) {
    map.record(out.len() as u32, with_fn.span);
    let _ = writeln!(out, "impl {} {{", s.name);
    let _ = write!(out, "    pub fn with(");
    for (i, name) in with_fn.fields.iter().enumerate() {
        if i > 0 {
            let _ = write!(out, ", ");
        }
        let _ = write!(out, "{name}: Option<{}>", format_ty(&s.fields[i].ty));
    }
    let _ = writeln!(out, ") -> Self {{");
    let _ = writeln!(out, "        Self {{");
    for (i, name) in with_fn.fields.iter().enumerate() {
        let default = with_fn.defaults[i]
            .as_ref()
            .map(emit_expr_inline)
            .unwrap_or_else(|| "Default::default()".into());
        let _ = writeln!(
            out,
            "            {name}: {name}.unwrap_or_else(|| {default}),"
        );
    }
    let _ = writeln!(out, "        }}");
    let _ = writeln!(out, "    }}");
    let _ = writeln!(out, "}}");
}

fn emit_enum(out: &mut String, e: &crisp_cir::CirEnum, map: &mut EmitSourceMap) {
    map.record(out.len() as u32, e.span);
    let vis = if e.is_pub { "pub " } else { "" };
    let _ = writeln!(out, "#[derive(Debug, Clone)]");
    let gens = if e.generics.is_empty() {
        String::new()
    } else {
        format!("<{}>", e.generics.join(", "))
    };
    let _ = writeln!(out, "{vis}enum {}{gens} {{", e.name);
    for v in &e.variants {
        emit_variant(out, v);
    }
    let _ = writeln!(out, "}}");
}

fn emit_variant(out: &mut String, v: &CirVariant) {
    if v.fields.is_empty() {
        let _ = writeln!(out, "    {},", v.name);
    } else {
        let tys: Vec<_> = v.fields.iter().map(format_ty).collect();
        let _ = writeln!(out, "    {}({}),", v.name, tys.join(", "));
    }
}

fn emit_shape_trait(out: &mut String, shape: &CirShapeTrait) {
    let gens = format_ty_params(&shape.generics);
    let _ = writeln!(out, "trait {}{gens} {{", shape.name);
    for (name, ty) in &shape.fields {
        let _ = writeln!(out, "    fn {name}(&self) -> {};", format_ty(ty));
    }
    for m in &shape.methods {
        let params: Vec<_> = m
            .params
            .iter()
            .map(|(n, t)| format!("{n}: {}", format_ty(t)))
            .collect();
        let _ = writeln!(
            out,
            "    fn {}({}) -> {};",
            m.name,
            params.join(", "),
            format_ty(&m.ret)
        );
    }
    let _ = writeln!(out, "}}");
    for imp in &shape.impls {
        let impl_gens = format_ty_params_bounded(&imp.ty_generics, "Clone");
        let args = format_ty_args(&imp.args);
        let ty = if imp.ty_generics.is_empty() {
            imp.ty_name.clone()
        } else {
            format!("{}<{}>", imp.ty_name, imp.ty_generics.join(", "))
        };
        let _ = writeln!(out, "impl{impl_gens} {}{args} for {ty} {{", shape.name);
        for (name, ty) in &shape.fields {
            let field_ty = subst_shape_field_ty(ty, &shape.generics, &imp.args);
            let body = shape_accessor_body(name, &field_ty);
            let _ = writeln!(
                out,
                "    fn {name}(&self) -> {} {{ {body} }}",
                format_ty(&field_ty)
            );
        }
        let _ = writeln!(out, "}}");
    }
    let _ = writeln!(out);
}

fn shape_accessor_body(name: &str, ty: &CirTy) -> String {
    match ty {
        CirTy::Int | CirTy::UInt | CirTy::Float | CirTy::Bool | CirTy::Char => {
            format!("self.{name}")
        }
        _ => format!("self.{name}.clone()"),
    }
}

fn emit_function(
    out: &mut String,
    f: &CirFunction,
    current_module: &str,
    map: &mut EmitSourceMap,
    allow_pub: bool,
    trait_impl: Option<&str>,
    cir: &CirCrate,
) {
    map.record(out.len() as u32, f.span);
    let vis = if allow_pub && f.is_pub { "pub " } else { "" };
    if f.is_main && f.is_async {
        let _ = writeln!(out, "#[tokio::main]");
    }
    let async_kw = if f.is_async { "async " } else { "" };
    let sig = format_fn_sig(f, trait_impl, cir);
    let _ = write!(out, "{vis}{async_kw}fn {}{sig} ", f.name);
    emit_block_body(out, &f.body, f.fallible, &f.ret, current_module, 0, map);
    let _ = writeln!(out);
}

fn format_fn_sig(f: &CirFunction, trait_impl: Option<&str>, cir: &CirCrate) -> String {
    let shape_names: std::collections::HashSet<&str> =
        cir.shape_traits.iter().map(|s| s.name.as_str()).collect();
    let mut type_params: Vec<String> = f
        .generics
        .iter()
        .map(|g| {
            let extras: Vec<String> = f
                .params
                .iter()
                .filter(|p| matches!(&p.ty, CirTy::Named { name, .. } if name == g))
                .flat_map(|p| p.extra_bounds.iter().cloned())
                .collect();
            format!("{g}: Clone{}", extra_bounds_suffix(&extras))
        })
        .collect();
    let mut params = Vec::new();
    let mut shape_i = 0usize;
    for p in &f.params {
        if let CirTy::Named { name, args } = &p.ty
            && shape_names.contains(name.as_str())
            && p.name != "self"
        {
            let tp = format!("S{shape_i}");
            shape_i += 1;
            let bound = if args.is_empty() {
                name.clone()
            } else {
                format!(
                    "{name}<{}>",
                    args.iter().map(format_ty).collect::<Vec<_>>().join(", ")
                )
            };
            type_params.push(format!(
                "{tp}: {bound}{}",
                extra_bounds_suffix(&p.extra_bounds)
            ));
            params.push(format_param_with_ty(p, &tp, trait_impl));
        } else {
            params.push(format_param(p, trait_impl));
        }
    }
    let generics = if type_params.is_empty() {
        String::new()
    } else {
        format!("<{}>", type_params.join(", "))
    };
    if f.is_async {
        return format!("{generics}({})", params.join(", "));
    }
    let ret = format_ret(&f.ret, f.fallible);
    format!("{generics}({}){}", params.join(", "), ret)
}

fn extra_bounds_suffix(bounds: &[String]) -> String {
    if bounds.is_empty() {
        String::new()
    } else {
        format!(" + {}", bounds.join(" + "))
    }
}

fn format_extern_param(p: &CirParam) -> String {
    format!("{}: {}", p.name, format_extern_ty(&p.ty))
}

fn format_extern_ty(ty: &CirTy) -> String {
    match ty {
        CirTy::Int | CirTy::UInt => "i32".into(),
        CirTy::Float => "f32".into(),
        CirTy::Bool => "bool".into(),
        other => format_ty(other),
    }
}

fn format_param(p: &CirParam, trait_impl: Option<&str>) -> String {
    if p.name == "self" {
        return match p.mode {
            OwnershipMode::Borrow => "&self".into(),
            OwnershipMode::MutBorrow => "&mut self".into(),
            OwnershipMode::Owned => "self".into(),
        };
    }
    if matches!(trait_impl, Some("Eq") | Some("Ord")) {
        return format!("{}: &Self", p.name);
    }
    let lt = p
        .lifetime
        .as_ref()
        .map(|l| format!("{l} "))
        .unwrap_or_default();
    let ty = match p.mode {
        OwnershipMode::Borrow
            if p.ty.is_stringish() || matches!(p.ty, CirTy::Str | CirTy::Var(_)) =>
        {
            format!("&{lt}str")
        }
        OwnershipMode::Borrow => format!("&{lt}{}", format_ty(&p.ty)),
        OwnershipMode::MutBorrow => format!("&{lt}mut {}", format_ty(&p.ty)),
        OwnershipMode::Owned => format_ty(&p.ty),
    };
    format!("{}: {ty}", p.name)
}

fn format_param_with_ty(p: &CirParam, ty_name: &str, trait_impl: Option<&str>) -> String {
    if p.name == "self" {
        return format_param(p, trait_impl);
    }
    let lt = p
        .lifetime
        .as_ref()
        .map(|l| format!("{l} "))
        .unwrap_or_default();
    let ty = match p.mode {
        OwnershipMode::Borrow => format!("&{lt}{ty_name}"),
        OwnershipMode::MutBorrow => format!("&{lt}mut {ty_name}"),
        OwnershipMode::Owned => ty_name.to_string(),
    };
    format!("{}: {ty}", p.name)
}

fn format_ret(ret: &CirTy, fallible: bool) -> String {
    if fallible {
        let inner = match ret {
            CirTy::Result { ok, .. } => format_ty(ok),
            other => format_ty(other),
        };
        format!(" -> Result<{inner}, CrispError>")
    } else if matches!(ret, CirTy::Unit) {
        String::new()
    } else {
        format!(" -> {}", format_ty(ret))
    }
}

fn emit_block_body(
    out: &mut String,
    block: &CirBlock,
    fn_fallible: bool,
    ret: &CirTy,
    current_module: &str,
    indent: usize,
    map: &mut EmitSourceMap,
) {
    let _ = writeln!(out, "{{");
    for stmt in &block.stmts {
        emit_stmt(out, stmt, current_module, indent + 1, map);
    }
    if let Some(tail) = &block.tail {
        let pad = "    ".repeat(indent + 1);
        if matches!(tail.as_ref(), CirExpr::Throw { .. }) {
            let _ = write!(out, "{pad}");
            emit_throw_stmt(out, tail, current_module, map);
            let _ = writeln!(out);
        } else if fn_fallible {
            let _ = write!(out, "{pad}Ok(");
            emit_expr(out, tail, current_module, map);
            let _ = writeln!(out, ")");
        } else if matches!(ret, CirTy::Unit) || tail_is_effect(tail) {
            let _ = write!(out, "{pad}");
            emit_expr(out, tail, current_module, map);
            let _ = writeln!(out, ";");
        } else {
            let _ = write!(out, "{pad}");
            emit_expr(out, tail, current_module, map);
            let _ = writeln!(out);
        }
    } else if fn_fallible {
        let pad = "    ".repeat(indent + 1);
        let _ = writeln!(out, "{pad}Ok(())");
    }
    let _ = write!(out, "}}");
}

fn emit_stmt(
    out: &mut String,
    stmt: &CirStmt,
    current_module: &str,
    indent: usize,
    map: &mut EmitSourceMap,
) {
    let pad = "    ".repeat(indent);
    match stmt {
        CirStmt::Let {
            name,
            mutable,
            value,
            span,
        } => {
            map.record(out.len() as u32, *span);
            let mut_kw = if *mutable || is_vec_new_expr(value) {
                "mut "
            } else {
                ""
            };
            let _ = write!(out, "{pad}let {mut_kw}{name} = ");
            emit_expr(out, value, current_module, map);
            let _ = writeln!(out, ";");
        }
        CirStmt::Expr(e) => {
            let _ = write!(out, "{pad}");
            if matches!(e, CirExpr::Throw { .. }) {
                emit_throw_stmt(out, e, current_module, map);
            } else {
                emit_expr(out, e, current_module, map);
            }
            let _ = writeln!(out, ";");
        }
        CirStmt::Assign {
            target,
            value,
            span,
        } => {
            map.record(out.len() as u32, *span);
            let _ = write!(out, "{pad}{target} = ");
            emit_expr(out, value, current_module, map);
            let _ = writeln!(out, ";");
        }
    }
}

fn emit_expr(out: &mut String, expr: &CirExpr, current_module: &str, map: &mut EmitSourceMap) {
    match expr {
        CirExpr::Unit { span } => {
            map.record(out.len() as u32, *span);
            let _ = write!(out, "()");
        }
        CirExpr::Int { value, span } => {
            map.record(out.len() as u32, *span);
            let _ = write!(out, "{value}");
        }
        CirExpr::Bool { value, span } => {
            map.record(out.len() as u32, *span);
            let _ = write!(out, "{value}");
        }
        CirExpr::Float { value, span } => {
            map.record(out.len() as u32, *span);
            if value.fract() == 0.0 {
                let _ = write!(out, "{value}.0");
            } else {
                let _ = write!(out, "{value}");
            }
        }
        CirExpr::Str { value, span } => {
            map.record(out.len() as u32, *span);
            let _ = write!(out, "\"{}\".to_string()", escape_str(value));
        }
        CirExpr::Ident { name, span, .. } => {
            map.record(out.len() as u32, *span);
            let _ = write!(out, "{name}");
        }
        CirExpr::BinOp {
            op,
            left,
            right,
            span,
            ..
        } => {
            map.record(out.len() as u32, *span);
            if *op == CirBinOp::Concat {
                let _ = write!(out, "format!(\"{{}}{{}}\", ");
                emit_expr(out, left, current_module, map);
                let _ = write!(out, ", ");
                emit_expr(out, right, current_module, map);
                let _ = write!(out, ")");
            } else if *op == CirBinOp::Pow {
                let _ = write!(out, "(");
                emit_expr(out, left, current_module, map);
                let _ = write!(out, ").powf(");
                emit_expr(out, right, current_module, map);
                let _ = write!(out, ")");
            } else {
                emit_expr(out, left, current_module, map);
                let _ = write!(out, " {} ", binop_rust(*op));
                emit_expr(out, right, current_module, map);
            }
        }
        CirExpr::Call {
            callee,
            module: callee_module,
            args,
            fallible,
            propagate_error,
            is_extern,
            span,
            ..
        } => {
            map.record(out.len() as u32, *span);
            emit_call_expr(
                out,
                callee,
                callee_module,
                args,
                *fallible,
                *propagate_error,
                *is_extern,
                current_module,
                map,
            );
        }
        CirExpr::StructLit {
            name,
            fields,
            all_fields,
            use_with,
            span,
            ..
        } => {
            map.record(out.len() as u32, *span);
            if *use_with {
                let _ = write!(out, "{name}::with(");
                let provided: std::collections::BTreeMap<_, _> = fields.iter().cloned().collect();
                for (i, fname) in all_fields.iter().enumerate() {
                    if i > 0 {
                        let _ = write!(out, ", ");
                    }
                    if let Some(val) = provided.get(fname) {
                        let _ = write!(out, "Some(");
                        emit_expr(out, val, current_module, map);
                        let _ = write!(out, ")");
                    } else {
                        let _ = write!(out, "None");
                    }
                }
                let _ = write!(out, ")");
            } else {
                let _ = write!(out, "{name} {{ ");
                for (i, (fname, val)) in fields.iter().enumerate() {
                    if i > 0 {
                        let _ = write!(out, ", ");
                    }
                    let _ = write!(out, "{fname}: ");
                    emit_expr(out, val, current_module, map);
                }
                let _ = write!(out, " }}");
            }
        }
        CirExpr::Throw { payload, span } => {
            map.record(out.len() as u32, *span);
            let _ = write!(out, "return Err(");
            emit_throw(out, payload, map);
            let _ = write!(out, ")");
        }
        CirExpr::Try { expr, span } => {
            map.record(out.len() as u32, *span);
            emit_expr(out, expr, current_module, map);
            let _ = write!(out, "?");
        }
        CirExpr::Catch {
            expr, arms, span, ..
        } => {
            map.record(out.len() as u32, *span);
            let _ = write!(out, "match ");
            emit_expr(out, expr, current_module, map);
            let _ = write!(out, " {{ Ok(v) => v,");
            for arm in arms {
                emit_catch_arm(out, arm, current_module, map);
            }
            let _ = write!(out, " }}");
        }
        CirExpr::Field {
            base, field, span, ..
        } => {
            map.record(out.len() as u32, *span);
            emit_expr(out, base, current_module, map);
            let _ = write!(out, ".{field}");
        }
        CirExpr::EnumVariant {
            ty_name,
            variant,
            args,
            span,
            ..
        } => {
            map.record(out.len() as u32, *span);
            let _ = write!(out, "{ty_name}::{variant}");
            if !args.is_empty() {
                let _ = write!(out, "(");
                for (i, arg) in args.iter().enumerate() {
                    if i > 0 {
                        let _ = write!(out, ", ");
                    }
                    emit_expr(out, arg, current_module, map);
                }
                let _ = write!(out, ")");
            }
        }
        CirExpr::AssocCall {
            ty_name,
            method,
            args,
            span,
            ..
        } => {
            map.record(out.len() as u32, *span);
            let _ = write!(out, "{ty_name}::{method}(");
            for (i, arg) in args.iter().enumerate() {
                if i > 0 {
                    let _ = write!(out, ", ");
                }
                emit_expr(out, arg, current_module, map);
            }
            let _ = write!(out, ")");
        }
        CirExpr::MethodCall {
            receiver,
            method,
            args,
            span,
            ..
        } => {
            map.record(out.len() as u32, *span);
            emit_expr(out, receiver, current_module, map);
            let _ = write!(out, ".{method}(");
            // Eq.equal / Ord.compare take `&Self`; auto-borrow args.
            let borrow_args = matches!(method.as_str(), "equal" | "compare");
            for (i, arg) in args.iter().enumerate() {
                if i > 0 {
                    let _ = write!(out, ", ");
                }
                if borrow_args && !matches!(arg, CirExpr::Borrow { .. }) {
                    let _ = write!(out, "&");
                }
                emit_expr(out, arg, current_module, map);
            }
            let _ = write!(out, ")");
        }
        CirExpr::Format { parts, span } => {
            map.record(out.len() as u32, *span);
            let _ = write!(out, "format!(\"");
            let mut args = Vec::new();
            for p in parts {
                match p {
                    crisp_cir::CirFormatPart::Lit(l) => {
                        let _ = write!(out, "{}", escape_format_lit(l));
                    }
                    crisp_cir::CirFormatPart::Expr(e) => {
                        let _ = write!(out, "{{}}");
                        args.push(e);
                    }
                }
            }
            let _ = write!(out, "\"");
            for e in args {
                let _ = write!(out, ", ");
                emit_expr(out, e, current_module, map);
            }
            let _ = write!(out, ")");
        }
        CirExpr::Clone { expr, span } => {
            map.record(out.len() as u32, *span);
            emit_expr(out, expr, current_module, map);
            let _ = write!(out, ".clone()");
        }
        CirExpr::Borrow {
            expr,
            mutable,
            span,
        } => {
            map.record(out.len() as u32, *span);
            let _ = write!(out, "&");
            if *mutable {
                let _ = write!(out, "mut ");
            }
            emit_expr(out, expr, current_module, map);
        }
        CirExpr::Print { arg, debug, span } => {
            map.record(out.len() as u32, *span);
            let fmt = if *debug { "{:?}" } else { "{}" };
            let _ = write!(out, "println!(\"{fmt}\", ");
            emit_expr(out, arg, current_module, map);
            let _ = write!(out, ")");
        }
        CirExpr::If {
            cond,
            then_branch,
            else_branch,
            span,
            ..
        } => {
            map.record(out.len() as u32, *span);
            let _ = write!(out, "if ");
            emit_expr(out, cond, current_module, map);
            let _ = write!(out, " {{ ");
            emit_expr(out, then_branch, current_module, map);
            if let Some(e) = else_branch {
                let _ = write!(out, " }} else {{ ");
                emit_expr(out, e, current_module, map);
            }
            let _ = write!(out, " }}");
        }
        CirExpr::Match {
            scrutinee,
            arms,
            span,
            ..
        } => {
            map.record(out.len() as u32, *span);
            let _ = write!(out, "match ");
            emit_expr(out, scrutinee, current_module, map);
            let _ = write!(out, " {{");
            for arm in arms {
                emit_match_arm(out, arm, current_module, map);
            }
            let _ = write!(out, " }}");
        }
        CirExpr::While { cond, body, span } => {
            map.record(out.len() as u32, *span);
            let _ = write!(out, "while ");
            emit_expr(out, cond, current_module, map);
            let _ = write!(out, " ");
            emit_expr_block(out, body, current_module, map);
        }
        CirExpr::For {
            pat,
            iter,
            body,
            span,
        } => {
            map.record(out.len() as u32, *span);
            // MVP: Crisp `vec` is `Vec<i64>`; iterate by copied values so `&Vec`
            // and owned `Vec` both yield `i64` (ownership may borrow the param).
            let _ = write!(out, "for ");
            emit_pat(out, pat);
            let _ = write!(out, " in (");
            emit_expr(out, iter, current_module, map);
            let _ = write!(out, ").iter().copied() ");
            emit_expr_block(out, body, current_module, map);
        }
        CirExpr::Loop { body, span } => {
            map.record(out.len() as u32, *span);
            let _ = write!(out, "loop ");
            emit_expr_block(out, body, current_module, map);
        }
        CirExpr::Break { value, span } => {
            map.record(out.len() as u32, *span);
            let _ = write!(out, "break");
            if let Some(v) = value {
                let _ = write!(out, " ");
                emit_expr(out, v, current_module, map);
            }
        }
        CirExpr::Continue { span } => {
            map.record(out.len() as u32, *span);
            let _ = write!(out, "continue");
        }
        CirExpr::Unsafe { body, span } => {
            map.record(out.len() as u32, *span);
            let _ = write!(out, "unsafe ");
            emit_expr_block(out, body, current_module, map);
        }
        CirExpr::Async { body, span } => {
            map.record(out.len() as u32, *span);
            let _ = write!(out, "async ");
            emit_expr(out, body, current_module, map);
        }
        CirExpr::Await { expr, span, .. } => {
            map.record(out.len() as u32, *span);
            emit_expr(out, expr, current_module, map);
            let _ = write!(out, ".await");
        }
        CirExpr::Spawn { expr, span } => {
            map.record(out.len() as u32, *span);
            let _ = write!(out, "tokio::spawn(");
            emit_expr(out, expr, current_module, map);
            let _ = write!(out, ")");
        }
        CirExpr::Block(b) => {
            emit_expr_block(out, &CirExpr::Block(b.clone()), current_module, map);
        }
    }
}

fn emit_expr_block(
    out: &mut String,
    expr: &CirExpr,
    current_module: &str,
    map: &mut EmitSourceMap,
) {
    if let CirExpr::Block(block) = expr {
        if let Some(tail) = &block.tail {
            let _ = write!(out, "{{ ");
            for stmt in &block.stmts {
                emit_stmt(out, stmt, current_module, 1, map);
            }
            emit_expr(out, tail, current_module, map);
            let _ = write!(out, " }}");
            return;
        }
        if block.stmts.len() == 1
            && let CirStmt::Expr(inner) = &block.stmts[0]
        {
            let _ = write!(out, "{{ ");
            emit_expr(out, inner, current_module, map);
            let _ = write!(out, " }}");
            return;
        }
        emit_block_body(out, block, false, &CirTy::Unit, current_module, 0, map);
        return;
    }
    emit_expr(out, expr, current_module, map);
}

fn is_vec_new_expr(expr: &CirExpr) -> bool {
    matches!(
        expr,
        CirExpr::Call {
            callee,
            module,
            ..
        } if callee == "new" && module.starts_with("std.vec")
    )
}

fn emit_vec_receiver(
    out: &mut String,
    expr: &CirExpr,
    current_module: &str,
    map: &mut EmitSourceMap,
) {
    match expr {
        CirExpr::Borrow { expr: inner, .. } => emit_vec_receiver(out, inner, current_module, map),
        CirExpr::Ident { name, span, .. } => {
            map.record(out.len() as u32, *span);
            let _ = write!(out, "{name}");
        }
        _ => emit_expr(out, expr, current_module, map),
    }
}

#[allow(clippy::too_many_arguments)]
fn emit_call_expr(
    out: &mut String,
    callee: &str,
    callee_module: &str,
    args: &[crisp_cir::CirCallArg],
    fallible: bool,
    propagate_error: bool,
    is_extern: bool,
    current_module: &str,
    map: &mut EmitSourceMap,
) {
    if is_extern {
        let _ = write!(out, "{callee}(");
        for (i, arg) in args.iter().enumerate() {
            if i > 0 {
                let _ = write!(out, ", ");
            }
            emit_expr(out, &arg.expr, current_module, map);
            let _ = write!(out, " as i32");
        }
        let _ = write!(out, ") as i64");
        return;
    }
    if let Some(path) = std_rust_path(callee_module, callee) {
        match path {
            "Vec::new" => {
                let _ = write!(out, "Vec::<i64>::new()");
            }
            "Vec::push" if args.len() >= 2 => {
                emit_vec_receiver(out, &args[0].expr, current_module, map);
                let _ = write!(out, ".push(");
                emit_expr(out, &args[1].expr, current_module, map);
                let _ = write!(out, ")");
            }
            "Vec::len" if !args.is_empty() => {
                emit_vec_receiver(out, &args[0].expr, current_module, map);
                let _ = write!(out, ".len() as i64");
            }
            "tokio::time::sleep" if !args.is_empty() => {
                let _ = write!(
                    out,
                    "tokio::time::sleep(tokio::time::Duration::from_millis("
                );
                emit_expr(out, &args[0].expr, current_module, map);
                let _ = write!(out, "))");
            }
            "std::net::parse_ip" if !args.is_empty() => {
                let _ = write!(out, "({{ match ");
                emit_call_arg(out, &args[0].expr, args[0].mode, current_module, map);
                let _ = write!(
                    out,
                    ".parse::<std::net::IpAddr>() {{ Ok(a) => a.to_string(), Err(_) => \"invalid\".to_string() }} }})"
                );
            }
            other => {
                let _ = write!(out, "{other}(");
                for (i, arg) in args.iter().enumerate() {
                    if i > 0 {
                        let _ = write!(out, ", ");
                    }
                    emit_call_arg(out, &arg.expr, arg.mode, current_module, map);
                }
                let _ = write!(out, ")");
                if fallible && propagate_error {
                    let _ = write!(out, "?");
                }
                return;
            }
        }
    } else if let Some(crate_name) = callee_module.strip_prefix("rust.") {
        emit_rust_crate_call(
            out,
            crate_name,
            callee,
            args,
            current_module,
            map,
            fallible,
            propagate_error,
        );
        return;
    } else {
        if callee_module != current_module && !callee_module.starts_with("std.") {
            // Crisp `math.vector` → Rust `math::vector` (#35).
            let rust_path = callee_module.replace('.', "::");
            let _ = write!(out, "{rust_path}::");
        }
        let _ = write!(out, "{callee}(");
        for (i, arg) in args.iter().enumerate() {
            if i > 0 {
                let _ = write!(out, ", ");
            }
            emit_call_arg(out, &arg.expr, arg.mode, current_module, map);
        }
        let _ = write!(out, ")");
    }
    if fallible && propagate_error {
        let _ = write!(out, "?");
    }
}

/// Emit a call into a `rust = true` Cargo dependency (spec §14.2).
/// Known Result-returning APIs map into `CrispError::Thrown` and use `?` when propagating.
#[allow(clippy::too_many_arguments)]
fn emit_rust_crate_call(
    out: &mut String,
    crate_name: &str,
    callee: &str,
    args: &[crisp_cir::CirCallArg],
    current_module: &str,
    map: &mut EmitSourceMap,
    fallible: bool,
    propagate_error: bool,
) {
    match (crate_name, callee) {
        ("serde_json", "from_str") => {
            let _ = write!(out, "serde_json::from_str::<serde_json::Value>(");
            for (i, arg) in args.iter().enumerate() {
                if i > 0 {
                    let _ = write!(out, ", ");
                }
                emit_call_arg(out, &arg.expr, arg.mode, current_module, map);
            }
            let _ = write!(out, ")");
            emit_rust_result_absorb(out, fallible, propagate_error);
        }
        ("serde_json", "to_string" | "to_string_pretty") => {
            let _ = write!(out, "serde_json::{callee}(");
            for (i, arg) in args.iter().enumerate() {
                if i > 0 {
                    let _ = write!(out, ", ");
                }
                emit_call_arg(out, &arg.expr, arg.mode, current_module, map);
            }
            let _ = write!(out, ")");
            emit_rust_result_absorb(out, fallible, propagate_error);
        }
        ("ureq", "get") => {
            // ureq::Error and io::Error differ — map each step into CrispError.
            let _ = write!(out, "({{ let __resp = ureq::get(");
            for (i, arg) in args.iter().enumerate() {
                if i > 0 {
                    let _ = write!(out, ", ");
                }
                emit_call_arg(out, &arg.expr, arg.mode, current_module, map);
            }
            if fallible && propagate_error {
                let _ = write!(
                    out,
                    ").call().map_err(|e| CrispError::Thrown(e.to_string()))?; __resp.into_string().map_err(|e| CrispError::Thrown(e.to_string()))? }})"
                );
            } else if fallible {
                let _ = write!(
                    out,
                    ").call(); match __resp {{ Ok(r) => r.into_string().map_err(|e| CrispError::Thrown(e.to_string())), Err(e) => Err(CrispError::Thrown(e.to_string())) }} }})"
                );
            } else {
                let _ = write!(
                    out,
                    ").call().expect(\"ureq::get\").into_string().expect(\"ureq::get body\") }})"
                );
            }
        }
        _ => {
            let _ = write!(out, "{crate_name}::{callee}(");
            for (i, arg) in args.iter().enumerate() {
                if i > 0 {
                    let _ = write!(out, ", ");
                }
                emit_call_arg(out, &arg.expr, arg.mode, current_module, map);
            }
            let _ = write!(out, ")");
        }
    }
}

fn emit_rust_result_absorb(out: &mut String, fallible: bool, propagate_error: bool) {
    if fallible {
        let _ = write!(out, ".map_err(|e| CrispError::Thrown(e.to_string()))");
        if propagate_error {
            let _ = write!(out, "?");
        }
    } else {
        // Defensive fallback if CIR failed to mark the call fallible.
        let _ = write!(out, ".expect(\"rust Result\")");
    }
}

fn emit_throw_stmt(
    out: &mut String,
    expr: &CirExpr,
    current_module: &str,
    map: &mut EmitSourceMap,
) {
    if let CirExpr::Throw { payload, .. } = expr {
        let _ = write!(out, "return Err(");
        emit_throw(out, payload, map);
        let _ = write!(out, ")");
    } else {
        emit_expr(out, expr, current_module, map);
    }
}

fn emit_match_arm(
    out: &mut String,
    arm: &crisp_cir::CirMatchArm,
    current_module: &str,
    map: &mut EmitSourceMap,
) {
    map.record(out.len() as u32, arm.span);
    let _ = write!(out, " ");
    emit_pat(out, &arm.pat);
    if let Some(g) = &arm.guard {
        let _ = write!(out, " if ");
        emit_expr(out, g, current_module, map);
    }
    let _ = write!(out, " => ");
    emit_expr(out, &arm.body, current_module, map);
    let _ = write!(out, ",");
}

fn emit_pat(out: &mut String, pat: &CirPat) {
    match pat {
        CirPat::Wildcard { .. } => {
            let _ = write!(out, "_");
        }
        CirPat::Ident { name, .. } => {
            let _ = write!(out, "{name}");
        }
        CirPat::Int { value, .. } => {
            let _ = write!(out, "{value}");
        }
        CirPat::Struct { name, fields, .. } => {
            let _ = write!(out, "{name} {{ ");
            for (i, (fname, fp)) in fields.iter().enumerate() {
                if i > 0 {
                    let _ = write!(out, ", ");
                }
                let _ = write!(out, "{fname}");
                if !matches!(fp, CirPat::Wildcard { .. }) {
                    let _ = write!(out, ": ");
                    emit_pat(out, fp);
                }
            }
            let _ = write!(out, " }}");
        }
        CirPat::Enum {
            ty_name,
            variant,
            args,
            ..
        } => {
            let _ = write!(out, "{ty_name}::{variant}");
            if !args.is_empty() {
                let _ = write!(out, "(");
                for (i, arg) in args.iter().enumerate() {
                    if i > 0 {
                        let _ = write!(out, ", ");
                    }
                    emit_pat(out, arg);
                }
                let _ = write!(out, ")");
            }
        }
    }
}

fn tail_is_effect(tail: &CirExpr) -> bool {
    matches!(tail, CirExpr::Print { .. })
}

fn emit_call_arg(
    out: &mut String,
    expr: &CirExpr,
    mode: crisp_ownership::OwnershipMode,
    current_module: &str,
    map: &mut EmitSourceMap,
) {
    if matches!(mode, crisp_ownership::OwnershipMode::Borrow) {
        if matches!(expr, CirExpr::Borrow { .. }) {
            emit_expr(out, expr, current_module, map);
            return;
        }
        if let CirExpr::Str { value, span } = expr {
            map.record(out.len() as u32, *span);
            let _ = write!(out, "\"{}\"", escape_str(value));
            return;
        }
        if let CirExpr::Float { value, span } = expr {
            map.record(out.len() as u32, *span);
            if value.fract() == 0.0 {
                let _ = write!(out, "&{value}.0");
            } else {
                let _ = write!(out, "&{value}");
            }
            return;
        }
        let _ = write!(out, "&");
    }
    emit_expr(out, expr, current_module, map);
}

fn emit_catch_arm(
    out: &mut String,
    arm: &CirCatchArm,
    current_module: &str,
    map: &mut EmitSourceMap,
) {
    map.record(out.len() as u32, arm.span);
    if arm.wildcard {
        let _ = write!(out, " Err(_) => ");
    } else {
        let _ = write!(out, " Err(e) => ");
    }
    emit_expr(out, &arm.body, current_module, map);
    let _ = write!(out, ",");
}

fn emit_throw(out: &mut String, payload: &CirExpr, map: &mut EmitSourceMap) {
    if let CirExpr::StructLit { name, fields, .. } = payload {
        let _ = write!(out, "CrispError::{name}({name} {{ ");
        for (i, (fname, val)) in fields.iter().enumerate() {
            if i > 0 {
                let _ = write!(out, ", ");
            }
            let _ = write!(out, "{fname}: ");
            emit_expr_inline_to(out, val);
        }
        let _ = write!(out, " }})");
    } else {
        let _ = write!(out, "CrispError::Thrown(\"error\".into())");
    }
    let _ = map;
}

fn emit_expr_inline(e: &CirExpr) -> String {
    let mut s = String::new();
    emit_expr_inline_to(&mut s, e);
    s
}

fn emit_expr_inline_to(out: &mut String, expr: &CirExpr) {
    match expr {
        CirExpr::Str { value, .. } => {
            let _ = write!(out, "\"{value}\".into()");
        }
        CirExpr::Int { value, .. } => {
            let _ = write!(out, "{value}");
        }
        CirExpr::Bool { value, .. } => {
            let _ = write!(out, "{value}");
        }
        CirExpr::Float { value, .. } => {
            if value.fract() == 0.0 {
                let _ = write!(out, "{value}.0");
            } else {
                let _ = write!(out, "{value}");
            }
        }
        _ => {
            let _ = write!(out, "Default::default()");
        }
    }
}

fn binop_rust(op: CirBinOp) -> &'static str {
    match op {
        CirBinOp::Add => "+",
        CirBinOp::Sub => "-",
        CirBinOp::Mul => "*",
        CirBinOp::Div => "/",
        CirBinOp::Eq => "==",
        CirBinOp::Ne => "!=",
        CirBinOp::Lt => "<",
        CirBinOp::Le => "<=",
        CirBinOp::Gt => ">",
        CirBinOp::Ge => ">=",
        CirBinOp::And => "&&",
        CirBinOp::Or => "||",
        CirBinOp::Pow => ".powf",
        CirBinOp::Concat => "+",
    }
}

fn format_ty_params(gens: &[String]) -> String {
    if gens.is_empty() {
        String::new()
    } else {
        format!("<{}>", gens.join(", "))
    }
}

fn format_ty_params_bounded(gens: &[String], bound: &str) -> String {
    if gens.is_empty() {
        String::new()
    } else {
        format!(
            "<{}>",
            gens.iter()
                .map(|g| format!("{g}: {bound}"))
                .collect::<Vec<_>>()
                .join(", ")
        )
    }
}

fn format_ty_args(args: &[CirTy]) -> String {
    if args.is_empty() {
        String::new()
    } else {
        format!(
            "<{}>",
            args.iter().map(format_ty).collect::<Vec<_>>().join(", ")
        )
    }
}

fn subst_shape_field_ty(ty: &CirTy, gens: &[String], args: &[CirTy]) -> CirTy {
    match ty {
        CirTy::Named { name, args: inner } if inner.is_empty() => gens
            .iter()
            .position(|g| g == name)
            .and_then(|i| args.get(i).cloned())
            .unwrap_or_else(|| ty.clone()),
        CirTy::Named { name, args: inner } => CirTy::Named {
            name: name.clone(),
            args: inner
                .iter()
                .map(|a| subst_shape_field_ty(a, gens, args))
                .collect(),
        },
        other => other.clone(),
    }
}

pub fn format_ty(ty: &CirTy) -> String {
    match ty {
        CirTy::Never => "!".into(),
        CirTy::Unit => "()".into(),
        CirTy::Bool => "bool".into(),
        CirTy::Int => "i64".into(),
        CirTy::UInt => "u64".into(),
        CirTy::Float => "f64".into(),
        CirTy::Char => "char".into(),
        CirTy::Str => "String".into(),
        CirTy::Var(_) => "String".into(),
        CirTy::Named { name, args } if args.is_empty() => match name.as_str() {
            "vec" => "Vec<i64>".into(),
            "map" => "std::collections::HashMap<String, i64>".into(),
            "set" => "std::collections::HashSet<i64>".into(),
            other => other.to_string(),
        },
        CirTy::Named { name, args } => format!(
            "{name}<{}>",
            args.iter().map(format_ty).collect::<Vec<_>>().join(", ")
        ),
        CirTy::Option(inner) => format!("Option<{}>", format_ty(inner)),
        CirTy::Result { ok, err } => format!("Result<{}, {err}>", format_ty(ok)),
        CirTy::Ref { mutable, inner } => {
            if *mutable {
                format!("&mut {}", format_ty(inner))
            } else {
                format!("&{}", format_ty(inner))
            }
        }
        CirTy::Boxed(inner) => format!("Box<{}>", format_ty(inner)),
        CirTy::Tuple(ts) => format!(
            "({})",
            ts.iter().map(format_ty).collect::<Vec<_>>().join(", ")
        ),
        CirTy::Error => "_".into(),
    }
}

fn escape_str(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}

fn escape_format_lit(s: &str) -> String {
    s.replace('{', "{{").replace('}', "}}").replace('"', "\\\"")
}
