[package]
name = "crisp-lsp"
description = "Language Server Protocol — powered by reveal (spec §16.3)"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
readme = "../../README.md"
rust-version.workspace = true

[[bin]]
name = "crisp-lsp"
path = "src/bin/crisp-lsp.rs"

[dependencies]
crisp-ast.workspace = true
crisp-parser.workspace = true
crisp-resolve.workspace = true
crisp-typeck.workspace = true
crisp-ownership.workspace = true
crisp-regions.workspace = true
crisp-errors.workspace = true
crisp-reveal.workspace = true
crisp-rust-emit.workspace = true
thiserror.workspace = true
anyhow.workspace = true
tower-lsp.workspace = true
tokio.workspace = true

[dev-dependencies]
insta = { version = "1", features = ["yaml"] }
